### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by bmicklea** [bmicklea/issuemanagementtest#1]
## Milestone Overview
- 

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.
## Schedule

This release will be an Eclipse-signed and marketed release  (...or...This release will be an unsigned development release available on GitHub only).
- Code complete milestone: target August 3
- GitHub release complete (QA verified) milestone: target August 5
- Eclipse signed release complete (IP verified) milestone: target August 8
- Release shipped milestone: target August 9
#### Code complete milestone
- [ ] Code complete
- [ ] Announce on che-dev that release endgame has begun - no merges
- [ ] Smoke tests started
- [ ] Release review information sent to Eclipse PMC (only if release will be shipped)
- [ ] IP logs and information sent to Eclipse Foundation (only if release will be shipped)
#### Release candidate created milestone
- [ ] Release candidate created
- [ ] Test cycles started
- [ ] Docs reviewed
#### GitHub release complete (QA verified) milestone
- [ ] Release complete
- [ ] Release notes updated
- [ ] Release information updated on GitHub
- [ ] Announce on che-dev that release is complete - merges allowed
#### Eclipse signed release complete (IP verified) milestone
- [ ] Release signed by Eclipse Foundation
- [ ] Release information updated on Eclipse.org
- [ ] Release uploaded to Eclipse.org servers
- [ ] Release updated on Bitnami
- [ ] Release updated on codenvy.com (Eclipse Che free cloud offering)
#### Release shipped milestone
- [ ] Post release information to che-dev mailing list
- [ ] Release blog live on che.eclipse.org
- [ ] Marketing email / social notifications
## Target Milestone Issues

The following issues are targeted for inclusion in the milestone. As issues are closed they are checked. Stretch goals are indicated with "_Stretch_" before the item.
#### Epics and Issues
- [ ] 
#### Technical Debt
- [ ] 
#### Bugs
- [ ] 
#### Investigations
- [ ]

**Comment by weinand** [comment]
@bmicklea-ce just for your information: all the github names (@xxxx) used in this issue will get notification when you edit.

**Comment by bmicklea-ce** [comment]
Very sorry weinand!  I copied the VS code milestone outline because I think it's really good and didn't notice the @'s embedded.  Shame on me, should have look closer...
